services:
  - type: web
    name: accountx-portal
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_SERVER
        value: smtp-relay.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USE_TLS
        value: "1"
      - key: SMTP_USERNAME
        value: ""
      - key: SMTP_PASSWORD
        value: ""
      - key: SENDER_EMAIL
        value: info@accountx.me
      - key: SENDER_NAME
        value: AccountX DOO
      - key: INBOX_EMAIL
        value: info@accountx.me
